### ISSUE TITLE
No implementation found for int com.microsoft.media.MMVRSurfaceView.createRenderer

### ISSUE THREAD

**Issue by ghostring31** [OfficeDev/skype-android-app-sdk-samples#22] opened 2016-11-28 06:31 UTC
When inflaiting view with MVVRSurfaceView on vide_fragment_layout app is crashing with error: 
FATAL EXCEPTION: main
                                                                       Process: example.com.skypetest, PID: 14717
                                                                       java.lang.RuntimeException: Unable to start activity ComponentInfo{example.com.skypetest/example.com.skypetest.meeting.MeetingActivity}: android.view.InflateException: Binary XML file line #24: Binary XML file line #24: Error inflating class com.microsoft.media.MMVRSurfaceView
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3253)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
                                                                           at android.app.ActivityThread.access$1100(ActivityThread.java:221)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:158)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                        Caused by: android.view.InflateException: Binary XML file line #24: Binary XML file line #24: Error inflating class com.microsoft.media.MMVRSurfaceView
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:551)
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
                                                                           at example.com.skypetest.meeting.videocall.VideoCallFragment.onCreateView(VideoCallFragment.java:84)
                                                                           at android.app.Fragment.performCreateView(Fragment.java:2281)
                                                                           at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:983)
                                                                           at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1163)
                                                                           at android.app.BackStackRecord.run(BackStackRecord.java:793)
                                                                           at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1552)
                                                                           at android.app.FragmentController.execPendingActions(FragmentController.java:325)
                                                                           at android.app.Activity.performStart(Activity.java:6914)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3216)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349) 
                                                                           at android.app.ActivityThread.access$1100(ActivityThread.java:221) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:158) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:7224) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                        Caused by: android.view.InflateException: Binary XML file line #24: Error inflating class com.microsoft.media.MMVRSurfaceView
                                                                           at android.view.LayoutInflater.createView(LayoutInflater.java:657)
                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716)
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:847)
                                                                           at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:855)
                                                                           at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:855)
                                                                           at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:527)
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
                                                                           at example.com.skypetest.meeting.videocall.VideoCallFragment.onCreateView(VideoCallFragment.java:84) 
                                                                           at android.app.Fragment.performCreateView(Fragment.java:2281) 
                                                                           at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:983) 
                                                                           at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1163) 
                                                                           at android.app.BackStackRecord.run(BackStackRecord.java:793) 
                                                                           at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1552) 
                                                                           at android.app.FragmentController.execPendingActions(FragmentController.java:325) 
                                                                           at android.app.Activity.performStart(Activity.java:6914) 
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3216) 
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349) 
                                                                           at android.app.ActivityThread.access$1100(ActivityThread.java:221) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:158) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:7224) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                        Caused by: java.lang.reflect.InvocationTargetException
                                                                           at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                           at android.view.LayoutInflater.createView(LayoutInflater.java:631)
                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776) 
                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:847) 
                                                                           at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:855) 
                                                                           at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:855) 
                                                                           at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:527) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
                                                                           at example.com.skypetest.meeting.videocall.VideoCallFragment.onCreateView(VideoCallFragment.java:84) 
                                                                           at android.app.Fragment.performCreateView(Fragment.java:2281) 
                                                                           at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:983) 
                                                                           at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1163) 
                                                                           at android.app.BackStackRecord.run(BackStackRecord.java:793) 
                                                                           at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1552) 
                                                                           at android.app.FragmentController.execPendingActions(FragmentController.java:325) 
                                                                           at android.app.Activity.performStart(Activity.java:6914) 
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3216) 
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349) 
                                                                           at android.app.ActivityThread.access$1100(ActivityThread.java:221) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:158) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:7224) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                        Caused by: java.lang.UnsatisfiedLinkError: No implementation found for int com.microsoft.media.MMVRSurfaceView.createRenderer(java.lang.Object) (tried Java_com_microsoft_media_MMVRSurfaceView_createRenderer and Java_com_microsoft_media_MMVRSurfaceView_createRenderer__Ljava_lang_Object_2)
                                                                           at com.microsoft.media.MMVRSurfaceView.createRenderer(Native Method)
                                                                           at com.microsoft.media.MMVRSurfaceView.<init>(MMVRSurfaceView.java:38)
                                                                           at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                           at android.view.LayoutInflater.createView(LayoutInflater.java:631) 
                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776) 
                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:847) 
                                                                           at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:855) 
                                                                           at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:855) 
                                                                           at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:527) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
                                                                           at example.com.skypetest.meeting.videocall.VideoCallFragment.onCreateView(VideoCallFragment.java:84) 
                                                                           at android.app.Fragment.performCreateView(Fragment.java:2281) 
                                                                           at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:983) 
                                                                           at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1163) 
                                                                           at android.app.BackStackRecord.run(BackStackRecord.java:793) 
                                                                           at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1552) 
                                                                           at android.app.FragmentController.execPendingActions(FragmentController.java:325) 
                                                                           at android.app.Activity.performStart(Activity.java:6914) 
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3216) 
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349) 
                                                                           at android.app.ActivityThread.access$1100(ActivityThread.java:221) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:158) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:7224) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by rahulyaa** [comment] 2016-12-02 20:08
Hi, I tried this on my side... can you confirm you have all the latest binaries and a rebuild produces the same issue?

**Comment by ghostring31** [comment] 2016-12-05 13:07
I use latest version of SDK 0.7.1 (In version 0.7.0.4 same problem)
If i comment MMVRSurfaceView in my XML file all OK.

**Comment by rahulyaa** [comment] 2016-12-07 21:52
@ghostring31 Have you looked at the sfbdemo sample? The sample works just fine. Could you please point out the difference to me between your app and the sample?

**Comment by ghostring31** [comment] 2016-12-08 06:14
The difference between the my app and sample is version of gradle build tools: 
-in my app gradle:2.2.2
-in samole gradle:2.1.0

**Comment by rahulyaa** [comment] 2017-01-12 01:44
@ghostring31 Picking up on this one again. Did moving to older gradle version work for you?

**Comment by ghostring31** [comment] 2017-01-20 06:46
All the same. Nothing changed

**Comment by Jayanth-P** [comment] 2017-04-11 06:52
Has anyone found a solution for this issue?

**Comment by 4brunu** [comment] 2017-04-21 16:09
The problem is that you are inflating the xml that contains this view `com.microsoft.media.MMVRSurfaceView` before instantiate `com.microsoft.office.sfb.appsdk.Application` and maybe `com.microsoft.office.sfb.appsdk.Conversation` (not sure if the last one is required).

**Closed** 2017-06-05 17:02 UTC
