### ISSUE TITLE
Failed to load native library

### ISSUE THREAD

**Issue by techlectdinesh** [OfficeDev/skype-android-app-sdk-samples#43] opened 2017-05-04 08:26 UTC
E/dalvikvm: dlopen("/data/app-lib/com.microsoft.office.sfb.sfbdemo-1/libacomo.so") failed: Cannot load library: soinfo_link_image(linker.cpp:1636): could not load library "libsqlcipher.so" needed by "libacomo.so"; caused by load_library(linker.cpp:746): library "libsqlcipher.so" not found
05-04 13:54:23.724 11460-11460/com.microsoft.office.sfb.sfbdemo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.microsoft.office.sfb.sfbdemo/com.microsoft.office.sfb.sfbdemo.MainActivity}: java.lang.RuntimeException: Failed to load native library
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2245)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2299)
                                                                                      at android.app.ActivityThread.access$700(ActivityThread.java:150)
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1280)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                      at android.os.Looper.loop(Looper.java:137)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5283)
                                                                                      at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                      at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
                                                                                      at dalvik.system.NativeStart.main(Native Method)
                                                                                   Caused by: java.lang.RuntimeException: Failed to load native library
                                                                                      at com.microsoft.office.sfb.appsdk.Application.LoadNativeLibrary(Application.java:129)
                                                                                      at com.microsoft.office.sfb.appsdk.Application.initialize(Application.java:71)
                                                                                      at com.microsoft.office.sfb.appsdk.Application.getInstance(Application.java:143)
                                                                                      at com.microsoft.office.sfb.sfbdemo.MainActivity.onCreate(MainActivity.java:57)
                                                                                      at android.app.Activity.performCreate(Activity.java:5283)
                                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097)
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2209)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2299) 
                                                                                      at android.app.ActivityThread.access$700(ActivityThread.java:150) 
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1280) 
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                      at android.os.Looper.loop(Looper.java:137) 
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5283) 
                                                                                      at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                      at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102) 
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869) 
                                                                                      at dalvik.system.NativeStart.main(Native Method)

**Comment by rahulyaa** [comment] 2017-05-05 15:48
Duplicate of the other issue

**Closed by rahulyaa** 2017-05-05 15:48 UTC
