### ISSUE TITLE
Video escalation between two ATTENDEES with Android devices not working

### ISSUE THREAD

**Issue by fabiomercorillo** [OfficeDev/skype-android-app-sdk-samples#49] opened 2017-06-13 10:06 UTC
Hi,
in my use case I make a video escalation between 2 attendees using Android devices. After video service started with success for each participant, 
in which everyone subscribe itself to the video streaming of the other participant, the video preview and the surface connected to the remote participant work fine for few seconds, 
but after rendering some video frames the video service of both participants change unexpectedly its status to DISCONNECTED. 
Tested on Samsung S6 (Android 6) and LG G5 (Android 7).

After restarting the video, the issue always reappears.

The same scenario between Android SDK (ATTENDEE) and Web SDK (LEADER) work fine without errors.

Thanks

**Comment by praween05** [comment] 2017-07-14 05:57
Hi,

I have tried the sample app by guest user joining app. When I joined with 2 Android devices. Both participants cannot see each other video but they can exchange messages with each other. The audio call is also not working. Can you please look at this issue.


Thanks

**Comment by jovillas** [comment] 2017-08-03 23:24
Closing this as duplicate of #50

**Closed by jovillas** 2017-08-03 23:24 UTC
Labels: duplicate
